# Generated by Django 4.2 on 2024-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropWDRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved_instructor', 'Approved'), ('not_approved_instructor', 'Not Approved'), ('processed', 'Processed')], default='requested', max_length=50)),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('instructor_note', models.TextField(blank=True, null=True)),
                ('ce_note', models.TextField(blank=True, null=True)),
                ('student_signature', models.JSONField(blank=True, null=True)),
                ('parent_signature', models.JSONField(blank=True, null=True)),
                ('instructor_signature', models.JSONField(blank=True, null=True)),
                ('counselor_signature', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_by', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.studentregistration')),
            ],
            options={
                'unique_together': {('registration',)},
            },
        ),
    ]
