# Generated by Django 4.2 on 2024-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_wd', '0002_alter_dropwdrequest_counselor_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropwdrequest',
            name='notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dropwdrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed')], default='requested', max_length=50),
        ),
    ]
