# Generated by Django 4.2 on 2025-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_wd', '0003_dropwdrequest_notes_alter_dropwdrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropwdrequest',
            name='instructor_note',
        ),
    ]
