# Generated by Django 4.2 on 2025-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_wd', '0004_remove_dropwdrequest_instructor_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropwdrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='requested', max_length=50),
        ),
    ]
